### ISSUE TITLE
Local faucet doesn't work

### ISSUE THREAD

**Issue by grothem** [scaffold-eth/eth-components#22]
Trying to send eth using the local faucet gives an invalid address error. I can open the wallet and send eth that way though.

Seems like it's not parsing the address correctly, because when I paste it in, it doesn't show the little address icon:

![image](https://user-images.githubusercontent.com/23554636/141892711-69af73d7-f454-48a0-a31b-3c34a0d734c6.png)

**Comment by ShravanSunder** [comment]
What version are you using?  Which scaffold eth trip and branch?

**Comment by grothem** [comment]
I just cloned the scaffold-eth-typescript repo, running on master branch

**Comment by grothem** [comment]
So looks like v2.1.3 of eth-components
