### ISSUE TITLE
address prop of Balance component could be optional

### ISSUE THREAD

**Issue by grothem** [scaffold-eth/eth-components#27]
Right now, the address input of the Balance component is defined as `string | undefined`

I think this could just be declared as optional, then it wouldn't have to be explicitly set as undefined if there is no address. This would clean up the templates:
![image](https://user-images.githubusercontent.com/23554636/142353944-9148656e-b8b1-4837-95cf-6f05565c9327.png)

**Comment by ShravanSunder** [comment]
good point

**Comment by grothem** [comment]
I was using the component so I could just display an eth amount. But maybe I'm thinking wrong here, because I could just pass in the address of the contract I'm getting the balance from. I'll take another look at it, maybe this could just get closed.

**Comment by ShravanSunder** [comment]
i think it could just be a separate display eth component without complicating the signatures of this one.
