### ISSUE TITLE
Transaction error message should be human readable for some circumstances

### ISSUE THREAD

**Issue by ssp6** [scaffold-eth/eth-components#36]
The error messages given can be difficult to understand, especially when first getting started.

Image below provided from Austin

![telegram-cloud-photo-size-1-5129860860934728121-x](https://user-images.githubusercontent.com/29690087/149818236-6d3b7800-f89e-4aa6-8680-e01c457ad788.jpg)

**Comment by kamikazebr** [comment]
on version 2.2.1 too in typescript i get that description on notifier
![image](https://user-images.githubusercontent.com/691510/150450146-a4fb841b-39d1-47dd-a617-e7c0eab2376e.png)

The code on v2
https://github.com/scaffold-eth/eth-components/blob/releases/v2/src/functions/transactor.ts#L147

It probably what your version its running.
https://github.com/scaffold-eth/eth-components/blob/next/src/functions/transactor.ts#L140

But it too its not acurate.

The correct one should be more checking, maybe using RegExp too.

![image](https://user-images.githubusercontent.com/691510/150450442-9e7f613f-19a8-40b4-8465-f5752a3e3002.png)

```javascript
err.data?.message?.match(/reverted with reason string \'(.*?)\'/)[1]
```

I not tested that, but i think it will get better errors description

**Comment by kamikazebr** [comment]
I make that work on v2!

Should be easy to transport that code to V3 too, but i dont have some easy way to test it for now.

On UI
![photo_2022-01-21_00-36-02](https://user-images.githubusercontent.com/691510/150466234-95213c8a-723f-43df-90d5-c76a879b69cf.jpg)

On Smart Contract
![photo_2022-01-21_00-36-07](https://user-images.githubusercontent.com/691510/150466427-1d51da2f-db3c-4da7-8313-bd27be6d9462.jpg)


I'll open some PR for that, its okay? @ShravanSunder

**Comment by ShravanSunder** [comment]
> I make that work on v2!
> 
> Should be easy to transport that code to V3 too, but i dont have some easy way to test it for now.
> 
> On UI ![photo_2022-01-21_00-36-02](https://user-images.githubusercontent.com/691510/150466234-95213c8a-723f-43df-90d5-c76a879b69cf.jpg)
> 
> On Smart Contract ![photo_2022-01-21_00-36-07](https://user-images.githubusercontent.com/691510/150466427-1d51da2f-db3c-4da7-8313-bd27be6d9462.jpg)
> 
> I'll open some PR for that, its okay? @ShravanSunder

yes this is great! ty!  @kamikazebr  please make any logic is wrapped in try catch so it doesn't explode the app incase ethers changes their error structure.

**Comment by kamikazebr** [comment]
>  doesn't explode the app

hahaha Yes i made it and too made some callback (filter) function to custom the message on the future too without need upgrade the whole packages.

I'll create of PR today

**Comment by kamikazebr** [comment]
Create the PR here https://github.com/scaffold-eth/eth-components/pull/38 If you could check, comment and review will be awesome @ShravanSunder @ssp6

**Comment by ShravanSunder** [comment]
@kamikazebr  great work! 🥳

**Comment by ShravanSunder** [comment]
@kamikazebr  i'll try to release another version later today.  and tag it stable after its tested with scaffold-eth-typescript next branch.
